### ISSUE TITLE
JS error /_addons/new_format_pack/web/editor.js:219 Uncaught (in promise) TypeError: Cannot read property '$$' of undefined

### ISSUE THREAD

**Issue by lucwastiaux** [hgiesel/anki_new_format_pack#2]
I'm running into an issue with building this addon and trying to run it with Anki 2.1.46 on Linux. I'm new to Svelte so I could be doing something wrong. I did npm install in the web directory, then went up one directory and did bin/compile.sh, then bin/zip.sh

        function init(component, options, instance2, create_fragment2, not_equal, props, append_styles, dirty = [-1]) {
          const parent_component = current_component;
          set_current_component(component);
          const $$ = component.$$ = {
            fragment: null,
            ctx: null,
            props,
            update: noop,
            not_equal,
            bound: blank_object(),
            on_mount: [],
            on_destroy: [],
            on_disconnect: [],
            before_update: [],
            after_update: [],
            context: new Map(parent_component ? parent_component.$$.context : options.context || []),
            callbacks: blank_object(),
            dirty,
            skip_bound: false,
            root: options.target || parent_component.$$.root
          };

line 219 in this case is this: 
`root: options.target || parent_component.$$.root`

**Comment by lucwastiaux** [comment]
Related: https://github.com/sveltejs/svelte/issues/6584

**Comment by lucwastiaux** [comment]
`"svelte": "3.39.0"` in package.json fixes it.

**Comment by dae** [comment]
Is this perhaps another example of problems with using Svelte across compilation units Henrik? I'm a bit worried this approach is not going to work for us if it's not a use case Svelte are trying to support.

**Comment by lucwastiaux** [comment]
@dae  can you elaborate on what you're referring to ? I was a bit surprised to see that the example addon can be built without having access to anki's source code, I fully expected I would have to someone link to Anki's repository of Svelte components.

**Comment by hgiesel** [comment]
This specific issue was because I was using a newer Svelte version in this add-on, then Anki uses. I've downgraded the Svelte that the add-on uses to `svelte@~3.38.2`, and it works.
