### ISSUE TITLE
Anki 2.1.50 beta rc2:  Uncaught (in promise) TypeError: Cannot read property 'toolbar' of undefined

### ISSUE THREAD

**Issue by luc-languagetools** [hgiesel/anki_new_format_pack#8]
checking out the latest master, then building with scripts/compile.sh and running this addon with Anki 2.1.50 rc2 results in the following output on the console when the editor opens:
`JS error /_anki/legacyPageData?id=139813063959744:1 Uncaught (in promise) TypeError: Cannot read property 'toolbar' of undefined`

Do I need a particular node or npm version when building ?

**Comment by hgiesel** [comment]
Was closed by #9
